name = "org-api-prod"
compatibility_date = "2024-05-11"
main = "src/index.ts"
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "AUTH", service = "auth-api-prod" },
  { binding = "INTL", service = "intl-api-prod" },
  { binding = "USERS", service = "users-api-prod" },
]
vars = { AUTH_URL = "https://auth-api-prod.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prod.uincmix.workers.dev/api/intl", USERS_URL = "https://users-api-prod.uincmix.workers.dev/api/users", COOKIE_NAME = "incmix_session", DOMAIN = ".uincmix.workers.dev" }
d1_databases = [
  { binding = "DB", database_name = "org-api", database_id = "acfc61ad-fc5f-44c4-8158-26afc7694f1b", migrations_dir = "./migrations/d1" },
]

[dev]
port = 9292

[env.dev]
name = "org-api-dev"
services = [
  { binding = "AUTH", service = "auth-api-dev" },
  { binding = "INTL", service = "intl-api-dev" },
  { binding = "USERS", service = "users-api-dev" },
]
vars = { AUTH_URL = "http://localhost:8787/api/auth", INTL_URL = "https://intl-api-dev.uincmix.workers.dev/api/intl", USERS_URL = "https://users-api-dev.uincmix.workers.dev/api/users", COOKIE_NAME = "incmix_session_dev", DOMAIN = "localhost" }
d1_databases = [
  { binding = "DB", database_name = "org-api-dev", database_id = "f7064129-b2fd-448d-bfc9-b982c0c2addc", migrations_dir = "./migrations/d1" },
]

[env.prev]
name = "org-api-dev-prev"
services = [
  { binding = "AUTH", service = "auth-api-dev-prev" },
  { binding = "INTL", service = "intl-api-dev-prev" },
  { binding = "USERS", service = "users-api-dev-prev" },
]
vars = { AUTH_URL = "https://auth-api-dev-prev.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prev.uincmix.workers.dev/api/intl", USERS_URL = "https://users-api-prev.uincmix.workers.dev/api/users", COOKIE_NAME = "incmix_session_prev", DOMAIN = ".uincmix.workers.dev" }
d1_databases = [
  { binding = "DB", database_name = "org-api-dev-prev", database_id = "b9913a31-7b46-42d2-9464-01b5064db9da", migrations_dir = "./migrations/d1" },
]

[env.test]
name = "org-api-test"
services = [
  { binding = "AUTH", service = "auth-api-dev-test" },
  { binding = "INTL", service = "intl-api-test" },
  { binding = "USERS", service = "users-api-test" },
]
vars = { AUTH_URL = "https://auth-api-dev-test.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-test.uincmix.workers.dev/api/intl", USERS_URL = "https://users-api-test.uincmix.workers.dev/api/users", SENTRY_DSN = "", COOKIE_NAME = "incmix_session_test", DOMAIN = "localhost" }
d1_databases = [
  { binding = "DB", database_name = "org-api-test", database_id = "00000000-0000-0000-0000-000000000000", migrations_dir = "./migrations/d1" },
]
