name = "users-api-prod"
compatibility_date = "2024-05-11"
main = "src/index.ts"
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"
compatibility_flags = ["nodejs_compat"]

vars = { AUTH_URL = "https://auth-api-prod.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prod.uincmix.workers.dev/api/intl", ORG_URL = "https://org-api-prod.uincmix.workers.dev/api/org", FILES_API_URL = "https://fs-api-prod.uincmix.workers.dev/api/files", COOKIE_NAME = "incmix_session", DOMAIN = ".uincmix.workers.dev" }

services = [
  { binding = "AUTH", service = "auth-api-prod" },
  { binding = "FILES_API", service = "fs-api-prod" },
  { binding = "INTL", service = "intl-api-prod" },
  { binding = "ORG", service = "org-api-prod" },
]
d1_databases = [
  { binding = "DB", database_name = "users-api", database_id = "91e3132c-c224-4a12-9604-41bb858d2346", migrations_dir = "./migrations/d1" },
]

[dev]
port = 9191

[env.dev]
name = "users-api-dev"
services = [
  { binding = "AUTH", service = "auth-api-dev" },
  { binding = "FILES_API", service = "fs-api-dev" },
  { binding = "INTL", service = "intl-api-dev" },
  { binding = "ORG", service = "org-api-dev" },
]
vars = { AUTH_URL = "http://localhost:8787/api/auth", INTL_URL = "http://localhost:9090/api/intl", ORG_URL = "http://localhost:9090/api/org", FILES_API_URL = "http://localhost:8282/api/files", COOKIE_NAME = "incmix_session_dev", DOMAIN = "localhost" }
d1_databases = [
  { binding = "DB", database_name = "users-api-dev", database_id = "7016d5dd-e10e-47df-abe4-782ac794f75b", migrations_dir = "./migrations/d1" },
]

[env.prev]
name = "users-api-dev-prev"
services = [
  { binding = "AUTH", service = "auth-api-dev-prev" },
  { binding = "FILES_API", service = "fs-api-dev-prev" },
  { binding = "INTL", service = "intl-api-dev-prev" },
  { binding = "ORG", service = "org-api-dev-prev" },
]
vars = { AUTH_URL = "https://auth-api-dev-prev.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prev.uincmix.workers.dev/api/intl", ORG_URL = "https://org-api-prev.uincmix.workers.dev/api/org", FILES_API_URL = "https://fs-api-dev-prev.uincmix.workers.dev/api/files", COOKIE_NAME = "incmix_session_prev", DOMAIN = ".uincmix.workers.dev" }
d1_databases = [
  { binding = "DB", database_name = "users-api-dev-prev", database_id = "40b6c9c6-ec0b-4c9b-9788-d5c77e4fe495", migrations_dir = "./migrations/d1" },
]

[env.test]
services = [
  { binding = "AUTH", service = "auth-api-dev-test" },
  { binding = "FILES_API", service = "fs-api-dev-test" },
  { binding = "INTL", service = "intl-api-test" },
]
vars = { AUTH_URL = "https://auth-api-dev-test.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-test.uincmix.workers.dev/api/intl", FILES_API_URL = "https://fs-api-test.uincmix.workers.dev/api/files", SENTRY_DSN = "", COOKIE_NAME = "incmix_session_test", DOMAIN = "localhost" }
d1_databases = [
  { binding = "DB", database_name = "users-api-test", database_id = "00000000-0000-0000-0000-000000000000", migrations_dir = "./migrations/d1" },
]
