# =============================================================================
# INCMIX PRODUCTION DOCKER COMPOSE
# =============================================================================
#
# This file is designed to work with Coolify deployment platform.
# All environment variables are now configurable via Coolify resource configuration.
#
# Each service only receives the environment variables it actually needs.
# No hardcoded values - everything is configurable.
#
# Required Environment Variables:
# - REDIS_PASSWORD: Password for Redis authentication (defaults to 'redis_password')
#
# =============================================================================

version: "3.8"
name: "incmix"

# Common environment variables used across multiple services
x-common-env: &common-env
  # Database
  DATABASE_URL: ${DATABASE_URL}
  # Service configuration
  NODE_ENV: ${NODE_ENV}
  COOKIE_NAME: ${COOKIE_NAME}
  DOMAIN: ${DOMAIN}
  # Frontend URL
  FRONTEND_URL: ${FRONTEND_URL}
  # Monitoring
  SENTRY_DSN: ${SENTRY_DSN:-https://examplePublicKey@o0.ingest.sentry.io/0}
  # Service configuration
  MOCK_DATA: ${MOCK_DATA:-false}
  TIMEOUT_MS: ${TIMEOUT_MS:-5000}
  # Service URLs
  AUTH_API_URL: ${AUTH_API_URL:-http://auth-api:8787/api/auth}
  ORG_API_URL: ${ORG_API_URL:-http://org-api:9292/api/org}
  INTL_API_URL: ${INTL_API_URL:-http://intl-api:9090/api/intl}
  EMAIL_API_URL: ${EMAIL_API_URL:-http://email-api:8989/api/email}
  FILES_API_URL: ${FILES_API_URL:-http://files-api:8282/api/files}
  GENAI_API_URL: ${GENAI_API_URL:-http://genai-api:8383/api/genai}
  PROJECTS_API_URL: ${PROJECTS_API_URL:-http://projects-api:8484/api/projects}
  COMMENTS_API_URL: ${COMMENTS_API_URL:-http://comments-api:8585/api/comments}
  LOCATION_API_URL: ${LOCATION_API_URL:-http://location-api:9494/api/location}
  RXDB_SYNC_API_URL: ${RXDB_SYNC_API_URL:-http://rxdb-api:8686/api/rxdb-sync}

services:
  postgres:
    image: registry.incmix.com/db:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_EXTENSIONS: plv8, btree_gist, hstore, pgvector, pgcrypto, CITEXT, pg_trgm, pg_cron, plpython3u
    # Internal access only - no external ports
    volumes:
      - incmix-db-data:/var/lib/postgresql/data
    networks:
      - incmix-network
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    restart: always
    command: --cluster_mode=emulated --lock_on_hashtags --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - incmix-dragonfly-data:/data
    networks:
      - incmix-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  auth-api:
    image: registry.incmix.com/auth-service:latest
    environment:
      <<: *common-env
      PORT: 8787
      # OAuth and authentication
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
    networks:
      - incmix-network
    depends_on:
      - postgres

  email-api:
    image: registry.incmix.com/email-service:latest
    environment:
      <<: *common-env
      PORT: 8989
      EMAIL_FROM: ${EMAIL_FROM}
      # Email service
      RESEND_API_KEY: ${RESEND_API_KEY}
    networks:
      - incmix-network
    depends_on:
      - postgres

  org-api:
    image: registry.incmix.com/org-api:latest
    environment:
      <<: *common-env
      PORT: 9292
    networks:
      - incmix-network
    depends_on:
      - postgres

  intl-api:
    image: registry.incmix.com/intl-api:latest
    environment:
      <<: *common-env
      PORT: 9090
    networks:
      - incmix-network
    depends_on:
      - postgres

  files-api:
    image: registry.incmix.com/files-api:latest
    environment:
      <<: *common-env
      PORT: 8282
      # AWS/S3 configuration
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT_URL_S3: ${AWS_ENDPOINT_URL_S3}
      BUCKET_NAME: ${BUCKET_NAME}
    networks:
      - incmix-network
    depends_on:
      - postgres

  genai-api:
    image: registry.incmix.com/genai-api:latest
    environment:
      <<: *common-env
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      PORT: 8383
      # AI/ML services
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}
      FIGMA_TOKEN: ${FIGMA_TOKEN}
    networks:
      - incmix-network
    depends_on:
      - postgres
      - redis

  projects-api:
    image: registry.incmix.com/projects-api:latest
    environment:
      <<: *common-env
      PORT: 8484
    networks:
      - incmix-network
    depends_on:
      - postgres

  location-api:
    image: registry.incmix.com/location-api:latest
    environment:
      <<: *common-env
      PORT: 9494
      # Location and weather services
      WEATHER_URL: ${WEATHER_URL}
      LOCATION_URL: ${LOCATION_URL}
      SERP_NEWS_URL: ${SERP_NEWS_URL}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      LOCATION_API_KEY: ${LOCATION_API_KEY}
      SERP_API_KEY: ${SERP_API_KEY}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    networks:
      - incmix-network
    depends_on:
      - postgres
      - redis

  comments-api:
    image: registry.incmix.com/comments-api:latest
    environment:
      <<: *common-env
      PORT: 8585
    networks:
      - incmix-network
    depends_on:
      - postgres

  rxdb-api:
    image: registry.incmix.com/rxdb-api:latest
    environment:
      <<: *common-env
      PORT: 8686

    networks:
      - incmix-network
    depends_on:
      - postgres

  bff-web:
    image: registry.incmix.com/bff-web:latest
    environment:
      <<: *common-env
      PORT: 8080
    ports:
      - 8081:8080  # Only public access point
    networks:
      - incmix-network
    depends_on:
      - postgres

volumes:
  incmix-db-data:
  incmix-dragonfly-data:
networks:
  incmix-network:
