name: "incmix"
x-api-common: &api-common
  environment:
    DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    TURBO_TOKEN: ${TURBO_TOKEN}
  env_file:
    - .services
  networks:
    - incmix-network
  depends_on:
    - postgres

services:
  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-incmix}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
      # POSTGRES_EXTENSIONS: plv8, btree_gist, hstore, pgvector, pgcrypto, CITEXT, pg_trgm, pg_cron, plpython3u
    ports:
      - ${POSTGRES_PORT:-54321}:5432
    volumes:
      - incmix-db-data:/var/lib/postgresql/data
    networks:
      - incmix-network
  # backend:
  #   image: electricsql/electric
  #   environment:
  #     DATABASE_URL: postgresql://postgres:password@postgres:5432/incmix?sslmode=disable
  #     ELECTRIC_INSECURE: true
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  auth-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/auth/Dockerfile
    ports:
      - 8787:8787
  email-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/email/Dockerfile
    ports:
      - 8989:8989
    depends_on:
      - auth-api
  users-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/users-api/Dockerfile
    ports:
      - 9191:9191
    depends_on:
      - email-api
  org-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/org-api/Dockerfile
    ports:
      - 9292:9292
    depends_on:
      - users-api
  intl-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/intl-api/Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - org-api
  files-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/files-api/Dockerfile
    ports:
      - 8282:8282
    depends_on:
      - intl-api
  genai-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/genai-api/Dockerfile
    ports:
      - 8383:8383
    depends_on:
      - files-api
  projects-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/projects-api/Dockerfile
    ports:
      - 8484:8484
    depends_on:
      - genai-api
  tasks-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/tasks-api/Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - projects-api
  location-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/location-api/Dockerfile
    ports:
      - 9494:9494
    depends_on:
      - tasks-api
  comments-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/comments-api/Dockerfile
    ports:
      - 8585:8585
    depends_on:
      - location-api
  rxdb-api:
    <<: *api-common
    build:
      context: .
      dockerfile: api/rxdb-api/Dockerfile
    ports:
      - 8686:8686
    depends_on:
      - comments-api
  bff-web:
    <<: *api-common
    build:
      context: .
      dockerfile: api/bff-web/Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - rxdb-api
volumes:
  incmix-db-data:

networks:
  incmix-network:
