name: "incmix"
services:
  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    # image: sibedge/postgres-plv8-bigint:17.4-3.2.3
    restart: always
    environment:
      POSTGRES_DB: incmix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_EXTENSIONS: plv8, btree_gist, hstore, pgvector, pgcrypto, CITEXT, pg_trgm, pg_cron, plpython3u
    ports:
      - 54321:5432
    # volumes:
    #   - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    # command:
    #   - postgres
    #   - -c
    #   - config_file=/etc/postgresql/postgresql.conf
  backend:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/incmix?sslmode=disable
      ELECTRIC_INSECURE: true
    ports:
      - 3000:3000
    depends_on:
      - postgres