# =============================================================================
# INCMIX PRODUCTION DOCKER COMPOSE
# =============================================================================
#
# This file is designed to work with Coolify deployment platform.
# All environment variables are now configurable via Coolify resource configuration.
#
# The services will automatically pick up environment variables from Coolify.
# No hardcoded values - everything is configurable.
#
# =============================================================================

version: "3.8"
name: "incmix"
x-api-common: &api-common
  environment:
    # Database
    DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # API URLs - configurable via Coolify environment variables
    AUTH_API_URL: ${AUTH_API_URL:-http://auth-api:8787/api/auth}
    EMAIL_API_URL: ${EMAIL_API_URL:-http://email-api:8989/api/email}
    USERS_API_URL: ${USERS_API_URL:-http://users-api:9191/api/users}
    INTL_API_URL: ${INTL_API_URL:-http://intl-api:9090/api/intl}
    ORG_API_URL: ${ORG_API_URL:-http://org-api:9292/api/org}
    FILES_API_URL: ${FILES_API_URL:-http://files-api:8282/api/files}
    TASKS_API_URL: ${TASKS_API_URL:-http://tasks-api:8888/api/tasks}
    LOCATION_API_URL: ${LOCATION_API_URL:-http://location-api:9494/api/location}
    GENAI_API_URL: ${GENAI_API_URL:-http://genai-api:8383/api/genai}
    PROJECTS_API_URL: ${PROJECTS_API_URL:-http://projects-api:8484/api/projects}
    PERMISSIONS_API_URL: ${PERMISSIONS_API_URL:-http://permissions-api:9393/api/permissions}
    RXDB_SYNC_API_URL: ${RXDB_SYNC_API_URL:-http://rxdb-api:8686/api/rxdb-sync}
    COMMENTS_API_URL: ${COMMENTS_API_URL:-http://comments-api:8585/api/comments}

    # Service configuration
    NODE_ENV: ${NODE_ENV}
    COOKIE_NAME: ${COOKIE_NAME}
    DOMAIN: ${DOMAIN}
    FRONTEND_URL: ${FRONTEND_URL}

    # OAuth and authentication
    GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
    GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

    # Email service (SendGrid)
    SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    SENDGRID_WEBHOOK_KEY: ${SENDGRID_WEBHOOK_KEY}

    # AWS/S3 configuration
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${AWS_REGION}
    AWS_ENDPOINT_URL_S3: ${AWS_ENDPOINT_URL_S3}
    BUCKET_NAME: ${BUCKET_NAME}

    # AI/ML services
    GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}
    ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    FIGMA_TOKEN: ${FIGMA_TOKEN}

    # Location and weather services
    LOCATION_API_KEY: ${LOCATION_API_KEY}
    LOCATION_URL: ${LOCATION_URL}
    WEATHER_API_KEY: ${WEATHER_API_KEY}
    WEATHER_URL: ${WEATHER_URL}

    # Search and news services
    SERP_API_KEY: ${SERP_API_KEY}
    SERP_NEWS_URL: ${SERP_NEWS_URL}

    # Redis configuration
    UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
    UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}

  networks:
    - incmix-network
  depends_on:
    - postgres

services:
  postgres:
    image: registry.incmix.com/db:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_EXTENSIONS: plv8, btree_gist, hstore, pgvector, pgcrypto, CITEXT, pg_trgm, pg_cron, plpython3u
    # Internal access only - no external ports
    volumes:
      - incmix-db-data:/var/lib/postgresql/data
    networks:
      - incmix-network
  # backend:
  #   image: electricsql/electric
  #   environment:
  #     DATABASE_URL: postgresql://postgres:password@postgres:5432/incmix?sslmode=disable
  #     ELECTRIC_INSECURE: true
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  auth-api:
    <<: *api-common
    image: registry.incmix.com/auth-service:latest
    # Internal access only - no external ports

  email-api:
    <<: *api-common
    image: registry.incmix.com/email-service:latest
    # Internal access only - no external ports

  users-api:
    <<: *api-common
    image: registry.incmix.com/users-api:latest
    # Internal access only - no external ports

  org-api:
    <<: *api-common
    image: registry.incmix.com/org-api:latest
    # Internal access only - no external ports

  permissions-api:
    <<: *api-common
    image: registry.incmix.com/permissions-api:latest
    # Internal access only - no external ports

  intl-api:
    <<: *api-common
    image: registry.incmix.com/intl-api:latest
    # Internal access only - no external ports

  files-api:
    <<: *api-common
    image: registry.incmix.com/files-api:latest
    # Internal access only - no external ports

  genai-api:
    <<: *api-common
    image: registry.incmix.com/genai-api:latest
    # Internal access only - no external ports

  projects-api:
    <<: *api-common
    image: registry.incmix.com/projects-api:latest
    # Internal access only - no external ports

  tasks-api:
    <<: *api-common
    image: registry.incmix.com/tasks-api:latest
    # Internal access only - no external ports

  location-api:
    <<: *api-common
    image: registry.incmix.com/location-api:latest
    # Internal access only - no external ports

  comments-api:
    <<: *api-common
    image: registry.incmix.com/comments-api:latest
    # Internal access only - no external ports

  rxdb-api:
    <<: *api-common
    image: registry.incmix.com/rxdb-api:latest
    # Internal access only - no external ports

  bff-web:
    <<: *api-common
    image: registry.incmix.com/bff-web:latest
    ports:
      - 8081:8080  # Only public access point

volumes:
  incmix-db-data:

networks:
  incmix-network:
