# fly.gateway.toml

# fly.toml app configuration file generated for monorepo-demo-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "location-incmix-api"
primary_region = "lax"

[build]
dockerfile = "api/location-api/Dockerfile"

[build.args]
PROJECT = "incmix-apis"

[http_service]
internal_port = 9494
force_https = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "512mb"
size = "shared-cpu-1x"

[env]
PORT = "9494"
AUTH_URL = "https://auth-incmix-api.fly.dev/api/auth"
INTL_URL = "https://intl-incmix-api.fly.dev/api/intl"
COOKIE_NAME = "incmix_session"
DOMAIN = "bff-web-incmix-api.fly.dev"
WEATHER_URL = "https://api.tomorrow.io/v4/weather"
LOCATION_URL = "https://api.geoapify.com/v1"
SERP_NEWS_URL = "https://serpapi.com/search.json"
