# fly.gateway.toml

# fly.toml app configuration file generated for monorepo-demo-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "users-incmix-api"
primary_region = "lax"

[build]
dockerfile = "api/users-api/Dockerfile"

[build.args]
PROJECT = "incmix-apis"

[http_service]
internal_port = 9191
force_https = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "512mb"
size = "shared-cpu-1x"

[env]
PORT = "9191"
ORG_URL = "https://org-incmix-api.fly.dev/api/org"
AUTH_URL = "https://auth-incmix-api.fly.dev/api/auth"
INTL_URL = "https://intl-incmix-api.fly.dev/api/intl"
FILES_API_URL = "https://files-incmix-api.fly.dev/api/files"
COOKIE_NAME = "incmix_session"
DOMAIN = "bff-web-incmix-api.fly.dev"
