packages:
  - api/*
  - shared/*

catalog:
  zod: 3.23.8
  hono: 4.6.16
  miniflare: 3.20241230.2
  vitest: 2.1.8
  wrangler: 3.99.0
  typescript: 5.7.3
  "@hono/zod-openapi": 0.18.3
  "@jsprtmnn/utils": 0.1.0
  "@types/node": 22.10.1
  "@cloudflare/workers-types": 4.20250109.0
  "@cloudflare/vitest-pool-workers": 0.6.4
