packages:
  - api/*
  - shared/*
  - db/

catalog:
  hono: 4.6.16
  lodash: 4.17.21
  kysely: 0.27.5
  kysely-ctl: 0.12.1
  luxon: 3.4.2
  nanoid: 3.3.8
  pg: 8.13.3
  pkg-types: 1.3.1
  prettier: 3.3.3
  vitest: 3.1.2
  vite-tsconfig-paths: 5.1.4
  tsc-alias: 1.8.11
  tsx: 4.19.3
  typescript: 5.7.3
  zod: 3.24.2
  dotenv: 16.5.0
  dotenv-expand: 12.0.2
  "@casl/ability": 6.7.3
  "@hono/node-server": 1.13.8
  "@hono/zod-openapi": 0.19.8
  "@hono/zod-validator": 0.7.0
  "@incmix/utils": 0.36.3
  "@playwright/test": 1.49.0
  "@types/lodash": 4.17.1
  "@types/luxon": 3.4.2
  "@types/node": 22.10.1
  "@types/pg": 8.11.11
  "@types/react": 19.0.12
