packages:
  - api/*
  - shared/*

catalog:
  zod: 3.23.8
  hono: 4.6.16
  vitest: 2.1.8
  typescript: 5.7.3
  kysely: 0.27.5
  pg: 8.13.3
  "@hono/zod-openapi": 0.18.3
  "@incmix/utils": 0.1.0
  "@types/node": 22.10.1
