packages:
  - api/*
  - shared/*
  - db/

catalog:
  '@casl/ability': 6.7.3
  '@fastify/compress': 8.1.0
  '@fastify/cookie': 11.0.2
  '@fastify/cors': 11.1.0
  '@fastify/helmet': 13.0.1
  '@fastify/oas': 11.3.0x
  '@fastify/rate-limit': 10.3.0
  '@fastify/sensible': 6.0.3
  '@fastify/static': 8.2.0
  '@fastify/swagger': 9.5.1
  '@fastify/swagger-ui': 5.2.3
  '@fastify/websocket': 11.2.0
  '@incmix/utils': 0.51.0
  '@playwright/test': 1.49.0
  '@types/lodash': 4.17.1
  '@types/luxon': 3.4.2
  '@types/node': 22.10.1
  '@types/pg': 8.11.11
  '@types/react': 19.0.12
  bullmq: 5.56.10
  dotenv: 16.5.0
  dotenv-expand: 12.0.2
  dotenv-mono: 1.5.0
  fastify: 5.6.0
  fastify-openapi-glue: 4.9.2
  fastify-plugin: 5.0.1
  fastify-type-provider-zod: 6.0.0
  kysely: 0.27.5
  kysely-ctl: 0.12.1
  lodash: 4.17.21
  luxon: 3.4.2
  nanoid: 3.3.8
  path: 0.12.7
  pg: 8.13.3
  pkg-types: 1.3.1
  prettier: 3.3.3
  redis: 5.8.2
  tsc-alias: 1.8.16
  tsx: 4.19.3
  typescript: 5.7.3
  vite-tsconfig-paths: 5.1.4
  vitest: 3.1.2
  zod: ^4.0
