name = "intl-api-prod"
compatibility_date = "2024-05-11"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"

services = [{ binding = "AUTH", service = "auth-api-prod" }]
vars = { AUTH_URL = "https://auth-api-prod.uincmix.workers.dev/api/auth", COOKIE_NAME = "incmix_session" }
d1_databases = [
  { binding = "DB", database_name = "intl-api", database_id = "661ba425-dba4-4ff1-9bf5-6613fc3ba82e", migrations_dir = "./migrations/d1" },
]

[dev]
port = 9090

[env.dev]
name = "intl-api-dev"
services = [{ binding = "AUTH", service = "auth-api-dev" }]
vars = { AUTH_URL = "http://localhost:8787/api/auth", COOKIE_NAME = "incmix_session_dev" }
d1_databases = [
  { binding = "DB", database_name = "intl-api-dev", database_id = "eb5c79b0-ab96-46e9-b3ac-aa98abc83623", migrations_dir = "./migrations/d1" },
]

[env.prev]
name = "intl-api-dev-prev"
services = [{ binding = "AUTH", service = "auth-api-dev-prev" }]
vars = { AUTH_URL = "https://auth-api-dev-prev.uincmix.workers.dev/api/auth", COOKIE_NAME = "incmix_session_prev" }
d1_databases = [
  { binding = "DB", database_name = "intl-api-prev", database_id = "8648cf32-3bd2-49e4-8b82-d0d87678c77f", migrations_dir = "./migrations/d1" },
]
