# fly.gateway.toml

# fly.toml app configuration file generated for monorepo-demo-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "email-incmix-api"
primary_region = "lax"

[build]
dockerfile = "../../api/email/Dockerfile"

[build.args]
PROJECT = "incmix-apis"

[http_service]
internal_port = 8989
force_https = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "512mb"
size = "shared-cpu-1x"

[env]
PORT = "8989"
INTL_URL = "https://intl-incmix-api.fly.dev/api/intl"
