# fly.gateway.toml

# fly.toml app configuration file generated for monorepo-demo-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "tasks-incmix-api"
primary_region = "lax"

[build]
dockerfile = "../../api/tasks-api/Dockerfile"

[build.args]
PROJECT = "incmix-apis"

[http_service]
internal_port = 8888
force_https = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "512mb"

[env]
PORT = "8888"
ORG_URL = "https://org-incmix-api.fly.dev/api/org"
AUTH_URL = "https://auth-incmix-api.fly.dev/api/auth"
INTL_URL = "https://intl-incmix-api.fly.dev/api/intl"
COOKIE_NAME = "incmix_session"
DOMAIN = "bff-web-incmix-api.fly.dev"
