# fly.gateway.toml

# fly.toml app configuration file generated for monorepo-demo-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "auth-incmix-api-prev"
primary_region = "lax"

[build]
dockerfile = "../../api/auth/Dockerfile"

[build.args]
PROJECT = "incmix-apis-prev"

[http_service]
internal_port = 8787
force_https = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "512mb"
size = "shared-cpu-1x"

[env]
PORT = "8787"
FRONTEND_URL = "https://turbo-mix.pages.dev"
EMAIL_URL = "https://email-incmix-api-prev.fly.dev/api/email"
USERS_API_URL = "https://users-incmix-api-prev.fly.dev/api/users"
COOKIE_NAME = "incmix_session_prev"
GOOGLE_REDIRECT_URL = "https://turbo-mix.pages.dev/auth/google"
DOMAIN = "bff-web-incmix-api-prev.fly.dev"
INTL_URL = "https://intl-incmix-api-prev.fly.dev/api/intl"
