# fly.gateway.toml

# fly.toml app configuration file generated for monorepo-demo-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "bff-web-incmix-api-prev"
primary_region = "lax"

[build]
dockerfile = "../../api/bff-web/Dockerfile"

[build.args]
PROJECT = "incmix-apis-prev"

[http_service]
internal_port = 8080
force_https = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "256mb"
size = "shared-cpu-1x"

[env]
PORT = "8080"
AUTH_URL = "https://auth-incmix-api-prev.fly.dev"
ORG_URL = "https://org-incmix-api-prev.fly.dev"
INTL_URL = "https://intl-incmix-api-prev.fly.dev"
TASKS_URL = "https://tasks-incmix-api-prev.fly.dev"
USERS_URL = "https://users-incmix-api-prev.fly.dev"
FILES_URL = "https://files-incmix-api-prev.fly.dev"
EMAIL_URL = "https://email-incmix-api-prev.fly.dev"
LOCATION_URL = "https://location-incmix-api-prev.fly.dev"
COOKIE_NAME = "incmix_session-prev"
DOMAIN = "bff-web-incmix-api.fly.dev"
