# fly.gateway.toml

# fly.toml app configuration file generated for monorepo-demo-gateway"
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = "intl-incmix-api-prev"
primary_region = "lax"

[build]
dockerfile = "../../api/intl-api/Dockerfile"

[build.args]
PROJECT = "incmix-apis-prev"

[http_service]
internal_port = 9090
force_https = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "512mb"
size = "shared-cpu-1x"
[env]
PORT = "9090"
AUTH_URL = "https://auth-incmix-api-prev.fly.dev/api/auth"
COOKIE_NAME = "incmix_session_prev"
DOMAIN = "bff-web-incmix-api-prev.fly.dev"
