-- VercelDB postgres version 16
CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE EXTENSION IF NOT EXISTS timestamp9
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS PLV8;
CREATE EXTENSION IF NOT EXISTS POSTGIS;

--CREATE EXTENSION IF NOT EXISTS POSTGIS_TOPOSPATIAL;
--CREATE EXTENSION IF NOT EXISTS POSTGIS_TIGER_GEOCODING;
--CREATE EXTENSION IF NOT EXISTS POSTGIS_TIGER_GEOCODING_US;
--CREATE EXTENSION IF NOT EXISTS POSTGIS_TIGER_GEOCODING_US_ADDRESS;
--CREATE EXTENSION IF NOT EXISTS POSTGIS_TIGER_GEOCODING_US_ADDRESS_V2;
CREATE EXTENSION IF NOT EXISTS PLPYTHON3U;

--CREATE EXTENSION IF NOT EXISTS PG_CRON;
--CREATE EXTENSION IF NOT EXISTS PG_PARTMAN;
--CREATE EXTENSION IF NOT EXISTS PG_STAT_STATEMENTS;
--CREATE EXTENSION IF NOT EXISTS PG_PIVOT;
--CREATE EXTENSION IF NOT EXISTS PG_REORG;
--CREATE EXTENSION IF NOT EXISTS PG_TAP;
--CREATE EXTENSION IF NOT EXISTS PG_TAIL;
--CREATE EXTENSION IF NOT EXISTS PG_TTS;
--CREATE EXTENSION IF NOT EXISTS PG_SEARCH;
--CREATE EXTENSION IF NOT EXISTS PG_WAL2JSON;
-- CREATE EXTENSION IF NOT EXISTS pglogical
--CREATE EXTENSION IF NOT EXISTS PG_WALMON;
--CREATE EXTENSION IF NOT EXISTS PG_WALMON_LOGICAL;
--CREATE EXTENSION IF NOT EXISTS PG_WALMON_REPLICATION;
CREATE EXTENSION IF NOT EXISTS PG_WALMON_REPLICATION_LOGICAL;

CREATE EXTENSION IF NOT EXISTS PG_WALMON_REPLICATION_PHYSICAL;

CREATE EXTENSION IF NOT EXISTS PG_WALMON_REPLICATION_PHYSICAL_LOGICAL;
