name = "bff-web-prod"
compatibility_date = "2024-05-11"
main = "src/index.ts"
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"
compatibility_flags = ["nodejs_compat"]

# Default Options for Production env
services = [
  { binding = "AUTH_API", service = "auth-api-prod" },
  { binding = "TODO_API", service = "tasks-api-prod" },
  { binding = "USERS_API", service = "users-api-prod" },
  { binding = "ORG_API", service = "org-api-prod" },
  { binding = "INTL_API", service = "intl-api-prod" },
  { binding = "FILES_API", service = "fs-api-prod" },
  { binding = "EMAIL_API", service = "email-api-prod" },
  { binding = "LOCATION_API", service = "location-api-prod" },
]
vars = { AUTH_URL = "https://auth-api-prod.uincmix.workers.dev", TODO_URL = "https://tasks-api-prod.uincmix.workers.dev", ORG_URL = "https://org-api-prod.uincmix.workers.dev", INTL_URL = "https://intl-api-prod.uincmix.workers.dev", USERS_URL = "https://users-api-prod.uincmix.workers.dev", EMAIL_URL = "https://email-api-prod.uincmix.workers.dev", FILES_URL = "https://fs-api-prod.uincmix.workers.dev", LOCATION_URL = "https://location-api-prod.uincmix.workers.dev" }

[dev]
port = 8080

[env.dev]
name = "bff-web-dev"
services = [
  { binding = "AUTH_API", service = "auth-api-dev" },
  { binding = "TODO_API", service = "tasks-api-dev" },
  { binding = "USERS_API", service = "users-api-dev" },
  { binding = "ORG_API", service = "org-api-dev" },
  { binding = "INTL_API", service = "intl-api-dev" },
  { binding = "FILES_API", service = "fs-api-dev" },
  { binding = "EMAIL_API", service = "email-api-dev" },
  { binding = "LOCATION_API", service = "location-api-dev" },
]
vars = { AUTH_URL = "http://localhost:8787", ORG_URL = "http://localhost:9292", INTL_URL = "http://localhost:9090", TODO_URL = "http://localhost:8888", USERS_URL = "http://localhost:9191", FILES_URL = "http://localhost:8282", EMAIL_URL = "http://localhost:8989", LOCATION_URL = "http://localhost:9494" }

[env.prev]
name = "bff-web-dev-prev"
services = [
  { binding = "AUTH_API", service = "auth-api-dev-prev" },
  { binding = "TODO_API", service = "tasks-api-dev-prev" },
  { binding = "USERS_API", service = "users-api-dev-prev" },
  { binding = "ORG_API", service = "org-api-dev-prev" },
  { binding = "INTL_API", service = "intl-api-dev-prev" },
  { binding = "FILES_API", service = "fs-api-dev-prev" },
  { binding = "EMAIL_API", service = "email-api-dev-prev" },
  { binding = "LOCATION_API", service = "location-api-dev-prev" },
]
vars = { AUTH_URL = "https://auth-api-dev-prev.uincmix.workers.dev", TODO_URL = "https://tasks-api-dev-prev.uincmix.workers.dev", ORG_URL = "https://org-api-dev-prev.uincmix.workers.dev", INTL_URL = "https://intl-api-dev-prev.uincmix.workers.dev", USERS_URL = "https://users-api-dev-prev.uincmix.workers.dev", EMAIL_URL = "https://email-api-dev-prev.uincmix.workers.dev", FILES_URL = "https://fs-api-dev-prev.uincmix.workers.dev", LOCATION_URL = "https://location-api-dev-prev.uincmix.workers.dev" }

[env.test]
name = "bff-web-dev-test"
services = [
  { binding = "AUTH_API", service = "auth-api-test" },
  { binding = "TODO_API", service = "tasks-api-test" },
  { binding = "USERS_API", service = "users-api-test" },
  { binding = "ORG_API", service = "org-api-test" },
  { binding = "INTL_API", service = "intl-api-test" },
  { binding = "FILES_API", service = "fs-api-test" },
  { binding = "EMAIL_API", service = "email-api-test" },
  { binding = "LOCATION_API", service = "location-api-test" },
]
vars = { AUTH_URL = "https://auth-api-test.uincmix.workers.dev", TODO_URL = "https://tasks-api-test.uincmix.workers.dev", ORG_URL = "https://org-api-test.uincmix.workers.dev", INTL_URL = "https://intl-api-test.uincmix.workers.dev", USERS_URL = "https://users-api-test.uincmix.workers.dev", EMAIL_URL = "https://email-api-test.uincmix.workers.dev", FILES_URL = "https://fs-api-test.uincmix.workers.dev", LOCATION_URL = "https://LOCATION-api-test.uincmix.workers.dev" }
