name = "location-api-prod"
compatibility_date = "2024-05-11"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"


# Default Options for Production env
vars = { INTL_URL = "https://intl-api-prod.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev", WEATHER_URL = "https://api.tomorrow.io/v4/weather", LOCATION_URL = "https://api.geoapify.com/v1", SERP_NEWS_URL = "https://serpapi.com/search.json", RATE_LIMIT = "1", RATE_LIMIT_PERIOD = "60" }
services = [{ binding = "INTL", service = "intl-api-prod" }]

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1001"

# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 1, period = 60 }


[dev]
port = 9494

[env.dev]
name = "location-api-dev"
services = [{ binding = "INTL", service = "intl-api-dev" }]
vars = { INTL_URL = "http://localhost:9090/api/intl", DOMAIN = "localhost", WEATHER_URL = "https://api.tomorrow.io/v4/weather", LOCATION_URL = "https://api.geoapify.com/v1", SERP_NEWS_URL = "https://serpapi.com/search.json", RATE_LIMIT = "1", RATE_LIMIT_PERIOD = "60" }


[env.prev]
name = "location-api-dev-prev"
vars = { INTL_URL = "https://intl-api-prev.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev", WEATHER_URL = "https://api.tomorrow.io/v4/weather", LOCATION_URL = "https://api.geoapify.com/v1", SERP_NEWS_URL = "https://serpapi.com/search.json", RATE_LIMIT = "1", RATE_LIMIT_PERIOD = "60" }
services = [{ binding = "INTL", service = "intl-api-dev-prev" }]


[env.test]
name = "location-api-test"
vars = { INTL_URL = "https://intl-api-test.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev" }
services = [{ binding = "INTL", service = "intl-api-test" }]

[env.qa]
name = "location-api-qa"
vars = { INTL_URL = "https://intl-api-qa.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev" }
services = [{ binding = "INTL", service = "intl-api-qa" }]

[env.qa-prev]
name = "location-api-qa-prev"
vars = { INTL_URL = "https://intl-api-qa-prev.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev" }
services = [{ binding = "INTL", service = "intl-api-qa-prev" }]

[env.uat]
name = "location-api-uat"
vars = { INTL_URL = "https://intl-api-uat.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev" }
services = [{ binding = "INTL", service = "intl-api-uat" }]

[env.uat-prev]
name = "location-api-uat-prev"
vars = { INTL_URL = "https://intl-api-uat-prev.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev" }
services = [{ binding = "INTL", service = "intl-api-uat-prev" }]

[env.prod-prev]
name = "location-api-prod-prev"
vars = { INTL_URL = "https://intl-api-prod-prev.uincmix.workers.dev/api/intl", DOMAIN = ".uincmix.workers.dev" }
services = [{ binding = "INTL", service = "intl-api-prod-prev" }]
