name = "fs-api-prod"
compatibility_date = "2024-06-05"
main = "src/index.ts"
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "AUTH", service = "auth-api-prod" },
  { binding = "INTL", service = "intl-api-prod" },
]
vars = { AUTH_URL = "https://auth-api-prod.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prod.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session", BUCKET_NAME = 'fs-api-prod-bucket' }

r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-prod-bucket' }]


[dev]
port = 8282

[env.dev]
name = "fs-api-dev"
services = [
  { binding = "AUTH", service = "auth-api-dev" },
  { binding = "INTL", service = "intl-api-dev" },
]
vars = { AUTH_URL = "http://localhost:8787/api/auth", INTL_URL = "http://localhost:9090/api/intl", COOKIE_NAME = "incmix_session_dev", BUCKET_NAME = 'fs-api-dev-bucket', PORT = 8282 }

r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-dev-bucket' }]

[env.prev]
name = "fs-api-dev-prev"
services = [
  { binding = "AUTH", service = "auth-api-dev-prev" },
  { binding = "INTL", service = "intl-api-dev-prev" },
]
vars = { AUTH_URL = "https://auth-api-dev-prev.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-dev-prev.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session_prev", BUCKET_NAME = 'fs-api-dev-prev-bucket' }
r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-dev-prev-bucket' }]

[env.test]
name = "fs-api-test"
services = [
  { binding = "AUTH", service = "auth-api-test" },
  { binding = "INTL", service = "intl-api-test" },
]
vars = { AUTH_URL = "https://auth-api-test.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-test.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session_test", BUCKET_NAME = 'fs-api-test-bucket', PORT = 8282 }
r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-test-bucket' }]

[env.qa]
name = "fs-api-qa"
services = [
  { binding = "AUTH", service = "auth-api-qa" },
  { binding = "INTL", service = "intl-api-qa" },
]
vars = { AUTH_URL = "https://auth-api-qa.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-qa.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session_qa", BUCKET_NAME = 'fs-api-dev-bucket' }
r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-qa-bucket' }]

[env.qa-prev]
name = "fs-api-qa-prev"
services = [
  { binding = "AUTH", service = "auth-api-qa-prev" },
  { binding = "INTL", service = "intl-api-qa-prev" },
]
vars = { AUTH_URL = "https://auth-api-qa-prev.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-qa-prev.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session_qa_prev", BUCKET_NAME = 'fs-api-qa-prev-bucket' }
r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-qa-prev-bucket' }]

[env.uat]
name = "fs-api-uat"
services = [
  { binding = "AUTH", service = "auth-api-uat" },
  { binding = "INTL", service = "intl-api-uat" },
]
vars = { AUTH_URL = "https://auth-api-uat.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-uat.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session_uat", BUCKET_NAME = 'fs-api-uat-bucket' }
r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-uat-bucket' }]

[env.uat-prev]
name = "fs-api-uat-prev"
services = [
  { binding = "AUTH", service = "auth-api-uat-prev" },
  { binding = "INTL", service = "intl-api-uat-prev" },
]
vars = { AUTH_URL = "https://auth-api-uat-prev.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-uat-prev.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session_uat_prev", BUCKET_NAME = 'fs-api-uat-prev-bucket' }
r2_buckets = [{ binding = 'MY_BUCKET', bucket_name = 'fs-api-uat-prev-bucket' }]

[env.prod-prev]
name = "fs-api-prod-prev"
services = [
  { binding = "AUTH", service = "auth-api-prod-prev" },
  { binding = "INTL", service = "intl-api-prod-prev" },
]
vars = { AUTH_URL = "https://auth-api-prod-prev.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prod-prev.uincmix.workers.dev/api/intl", COOKIE_NAME = "incmix_session_prod_prev", BUCKET_NAME = 'fs-api-prod-prev-bucket' }
r2_buckets = [
  { binding = 'MY_BUCKET', bucket_name = 'fs-api-prod-prev-bucket' },
]
