name = "email-api-prod"
compatibility_date = "2024-05-11"
main = "src/index.ts"
node_compat = true
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"

services = [{ binding = "INTL", service = "intl-api-prod" }]
vars = { INTL_URL = "https://intl-api-prod.uincmix.workers.dev/api/intl" }
d1_databases = [
  { binding = "DB", database_name = "email-api", database_id = "98e9e03a-3400-4e97-85c5-d031a4efae1a", migrations_dir = "./migrations/d1" },
]

[triggers]
# Runs every 30 minute
crons = ["*/30 * * * *"]

[dev]
port = 8989

[env.dev]
name = "email-api-dev"
services = [{ binding = "INTL", service = "intl-api-dev" }]
vars = { INTL_URL = "http://localhost:9090/api/intl" }
d1_databases = [
  { binding = "DB", database_name = "email-api-dev", database_id = "f90e7630-8da5-4d6f-bade-43c1c7c2c2c0", migrations_dir = "./migrations/d1" },
]


[env.prev]
name = "email-api-dev-prev"
services = [{ binding = "INTL", service = "intl-api-dev-prev" }]
vars = { INTL_URL = "https://intl-api-dev-prev.uincmix.workers.dev/api/intl" }
d1_databases = [
  { binding = "DB", database_name = "email-api-dev-prev", database_id = "5c33cca5-c15f-4e4e-95c6-dc6bc164af5a", migrations_dir = "./migrations/d1" },
]

[env.qa]
name = "email-api-qa"

[env.qa-prev]
name = "email-api-qa-prev"

[env.uat]
name = "email-api-uat"

[env.uat-prev]
name = "email-api-uat-prev"

[env.prod-prev]
name = "email-api-prod-prev"
