name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: "incmix"
      SENTRY_PROJECT: "incmix-be-prod"
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_SECRET }}
      CLOUDFLARE_ACCOUNT_ID: "337b73d40247ca97f4eaa7ea3dfc96df"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Upload Sourcemaps
        run: bash ./prod.sh


