name: Deploy to Preview

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      # SENTRY_ORG: "incmix"
      # SENTRY_PROJECT: "incmix-be-prev"
      # CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_SECRET }}
      # CLOUDFLARE_ACCOUNT_ID: "337b73d40247ca97f4eaa7ea3dfc96df"
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Apis
        run: bash ./prev.sh
  # run_e2e_tests:
  #   needs: [deploy]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   name: Run E2E tests
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pnpm/action-setup@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22.13.0
  #         cache: 'pnpm'
  #     - name: Install Dependencies
  #       run: pnpm install
  #     - name: Install Playwright Browsers
  #       run: pnpx playwright install --with-deps
  #     - name: Run Playwright tests
  #       run: pnpm test:e2e
  # add_comment:
  #   needs: [deploy]
  #   runs-on: ubuntu-latest
  #   name: Add Comments
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/github-script@v7
  #       with:
  #         script: |
  #           const script = require('./.github/workflows/scripts/add-comment.js')
  #           await script({github,context,core})


