name: Migrate Production Env

on:
  push:
    branches:
      - main
    paths:
      - "api/*/migrations/*.sql"
      - ".github/workflows/prod-migrate.yaml"

jobs:
  migrate_auth:
    runs-on: ubuntu-latest
    name: Migrate Auth
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/migrate-d1
        with:
          workingDirectory: "api/auth"
          dbName: "lucia-auth"
  migrate_users:
    runs-on: ubuntu-latest
    name: Migrate Users
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/migrate-d1
        with:
          workingDirectory: "api/users-api"
          dbName: "users-api"
  migrate_org:
    runs-on: ubuntu-latest
    name: Migrate Org
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/migrate-d1
        with:
          workingDirectory: "api/org-api"
          dbName: "org-api"
  migrate_intl:
    runs-on: ubuntu-latest
    name: Migrate Intl
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/migrate-d1
        with:
          workingDirectory: "api/intl-api"
          dbName: "intl-api"
  migrate_email:
    runs-on: ubuntu-latest
    name: Migrate Email
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/migrate-d1
        with:
          workingDirectory: "api/email"
          dbName: "email-api"
  migrate_tasks:
    needs: [migrate_auth]
    runs-on: ubuntu-latest
    name: Migrate Tasks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/migrate-d1
        with:
          workingDirectory: "api/tasks-api"
          dbName: "tasks-api"
