name: Run Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "api/auth/**"
      - "api/org-api/**"
      - ".github/workflows/test.yaml"
jobs:
  unit_test:
    runs-on: ubuntu-latest
    name: Unit Test
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli -a redis_password ping || redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        cmd: redis-server --requirepass redis_password
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build utils
        run: pnpm build --filter=./shared/utils
      - name: Build test-utils
        run: pnpm build --filter=./shared/test-utils
      - name: Run tests
        run: pnpm run test:integration
        env:
          REDIS_URL: redis://:redis_password@localhost:6379


