name: "Vulnerability Scan"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'typescript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

#    - name: Run pnpm audit
#      id: pnpm_audit
#      run: |
#          AUDIT_OUTPUT=$(pnpm audit || true)
#          echo "AUDIT_OUTPUT<<EOF" >> $GITHUB_ENV
#          echo "$AUDIT_OUTPUT" >> $GITHUB_ENV
#          echo "EOF" >> $GITHUB_ENV
#      continue-on-error: true
#
    - name: Add PR Comment
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request' && (success() || failure())
      with:
        script: |
          const fs = require('fs');
          const { owner, repo, number } = context.issue;

          const auditOutput = process.env.AUDIT_OUTPUT || 'No audit output available';

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: `## Security Scan Results

            CodeQL scan completed.

            ### NPM Audit Summary
            \`\`\`
            ${auditOutput}
            \`\`\`

            Please review any security findings before merging.`
          });
