name = "tasks-api-prod"
compatibility_date = "2024-05-11"
main = "src/index.ts"
account_id = "337b73d40247ca97f4eaa7ea3dfc96df"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "AUTH", service = "auth-api-prod" },
  { binding = "INTL", service = "intl-api-prod" },
  { binding = "ORG", service = "org-api-prod" },
]
vars = { AUTH_URL = "https://auth-api-prod.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prod.uincmix.workers.dev/api/intl", ORG_URL = "https://org-api-prod.uincmix.workers.dev/api/org", COOKIE_NAME = "incmix_session", DOMAIN = ".uincmix.workers.dev" }
d1_databases = [
  { binding = "DB", database_name = "tasks-api-prod", database_id = "4d203f90-1b0c-4ec7-b972-b8ff41ab49d7", migrations_dir = "./migrations/d1" },
]

[dev]
port = 8888

[env.dev]
name = "tasks-api-dev"
services = [
  { binding = "AUTH", service = "auth-api-dev" },
  { binding = "INTL", service = "intl-api-dev" },
  { binding = "ORG", service = "org-api-dev" },
]
vars = { AUTH_URL = "http://localhost:8787/api/auth", INTL_URL = "http://localhost:9090/api/intl", ORG_URL = "http://localhost:9292/api/org", COOKIE_NAME = "incmix_session_dev", DOMAIN = "localhost" }
d1_databases = [
  { binding = "DB", database_name = "tasks-api-dev", database_id = "ec39f963-60d7-479e-bcf4-2782547f61b1", migrations_dir = "./migrations/d1" },
]

[env.prev]
name = "tasks-api-dev-prev"
services = [
  { binding = "AUTH", service = "auth-api-dev-prev" },
  { binding = "INTL", service = "intl-api-dev-prev" },
  { binding = "ORG", service = "org-api-dev-prev" },
]
vars = { AUTH_URL = "https://auth-api-dev-prev.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-prev.uincmix.workers.dev/api/intl", ORG_URL = "https://org-api-dev-prev.uincmix.workers.dev/api/org", COOKIE_NAME = "incmix_session_prev", DOMAIN = ".uincmix.workers.dev" }
d1_databases = [
  { binding = "DB", database_name = "tasks-api-dev-prev", database_id = "db482c03-0f05-44c9-b875-d8b48ebb3633", migrations_dir = "./migrations/d1" },
]

[env.test]
services = [
  { binding = "AUTH", service = "auth-api-dev-test" },
  { binding = "INTL", service = "intl-api-test" },
  { binding = "ORG", service = "org-api-test" },
]
vars = { AUTH_URL = "https://auth-api-dev-test.uincmix.workers.dev/api/auth", INTL_URL = "https://intl-api-test.uincmix.workers.dev/api/intl", ORG_URL = "https://org-api-test.uincmix.workers.dev/api/org", SENTRY_DSN = "", COOKIE_NAME = "incmix_session_test", DOMAIN = "localhost" }
d1_databases = [
  { binding = "DB", database_name = "tasks-api-test", database_id = "00000000-0000-0000-0000-000000000000", migrations_dir = "./migrations/d1" },
]
